name: Test Build

on:
  push:
    branches: [ main, develop, ui-ux-improvements ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pytest
    
    - name: Run tests (if any)
      run: |
        # Add pytest commands here when tests are added
        echo "No tests yet"
    
    - name: Test PyInstaller build
      run: |
        pyinstaller --onefile --noconsole --name="WordCloudMagic-Test" --icon="icons/icon_256.ico" --add-data="assets;assets" --add-data="configs;configs" --add-data="templates;templates" wordcloud_app.py
    
    - name: Check executable exists
      run: |
        if (Test-Path "dist/WordCloudMagic-Test.exe") {
          $size = (Get-Item "dist/WordCloudMagic-Test.exe").Length / 1MB
          Write-Host "✓ Build successful! Executable size: $([math]::Round($size, 2)) MB"
        } else {
          Write-Host "✗ Build failed! Executable not found."
          exit 1
        }